image: cypress/base:10
options:
  max-time: 10
pipelines:
  default:
  - step:
      name: Install dependencies
      caches:
        - npm
        - cypress
        - node
      script:
        - npm ci
  - parallel:
    # run these jobs in parallel so they load balance all specs
    # TODO how can we copy these settings easily?
    - step:
        name: E2E tests
        caches:
          - node
          - cypress
        script:
          - npx @bahmutov/print-env BITBUCKET
          - npm run start:ci &
          - npm run e2e:record -- --parallel --ci-build-id $BITBUCKET_BUILD_NUMBER
    - step:
        name: E2E tests
        caches:
          - node
          - cypress
        script:
          - npx @bahmutov/print-env BITBUCKET
          - npm run start:ci &
          - npm run e2e:record -- --parallel --ci-build-id $BITBUCKET_BUILD_NUMBER
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress