image: cypress/base:10
options:
  max-time: 10
pipelines:
  default:
  - step:
      name: Install dependencies
      caches:
        - npm
        - cypress
      script:
        - npm ci
  - parallel:
    - step:
        name: E2E tests
        caches:
          - npm
          - cypress
        script:
          - npx @bahmutov/print-env BITBUCKET
          - npm run start:ci & npm run e2e:record -- --parallel --group $BITBUCKET_BUILD_NUMBER
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress