image: cypress/base:10
options:
  max-time: 10
pipelines:
  default:
  - step:
      name: E2E tests
      caches:
        - npm
        - cypress
      script:
        - npm ci
        - npm run test:ci:record
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress